### ISSUE TITLE
[FEATURE REQUEST]Android Support

### ISSUE THREAD

**Issue by Cuphead74832** [nomnomab/unity-project-patcher#1]
Attemped to decompile Chicken Gun (v1.2.6 since further is ilc2pp) but only works for computers.
Also attemped to decompile this game, https://jamroca92.itch.io/grandprix-el-juego-del-verano but exe was not found.
Game Exe Path does not exist
UnityEngine.Debug:LogError (object)
Nomnom.UnityProjectPatcher.UPPatcherSettings:GetGameVersion () (at ./Library/PackageCache/com.nomnom.unity-project-patcher@db0e232801/Runtime/UPPatcherSettings.cs:110)
System.Reflection.MethodBase:Invoke (object,object[])
EditorAttributes.Editor.InlineButtonDrawer:OnGUI (UnityEngine.Rect,UnityEditor.SerializedProperty,UnityEngine.GUIContent) (at ./Library/PackageCache/com.nomnom.unity-project-patcher@db0e232801/Libs/EditorAttributes/Editor/Scripts/Drawers/InlineButtonDrawer.cs:25)
UnityEditor.Editor:DrawDefaultInspector ()
EditorAttributes.Editor.EditorExtension:OnInspectorGUI () (at ./Library/PackageCache/com.nomnom.unity-project-patcher@db0e232801/Libs/EditorAttributes/Editor/Scripts/EditorExtension.cs:42)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
How do i fix?

**Comment by nomnomab** [comment]
You have to actually fill in information in the various settings files + make a custom game wrapper. This core is just a bundle of tools.

https://github.com/nomnomab/unity-project-patcher?tab=readme-ov-file#usage
