### ISSUE TITLE
[ISSUE] Game wrapper not found?

### ISSUE THREAD

**Issue by Cuphead74832** [nomnomab/unity-project-patcher#2]
![image](https://github.com/nomnomab/unity-project-patcher/assets/119815517/6db7ef44-47f9-4097-89b4-38f78a95ac83)

**Comment by nomnomab** [comment]
> This core tool doesn't patch any game by itself itself, as it's just a core utility. Game wrappers have to utilize this core to set up its pipeline, and any specific fixing for that specific game.

**Comment by Cuphead74832** [comment]
So error fix? You should released a video to demo the tool btw. For noobies

**Comment by Cuphead74832** [comment]
This is harder than the README, please release a video demo for easier understanding.

**Comment by ArjixWasTaken** [comment]
> This is harder than the README, please release a video demo for easier understanding.

![image](https://github.com/user-attachments/assets/aed7f564-4f0b-4e33-bf24-692d53070efc)

**Comment by ArjixWasTaken** [comment]
What is harder than the README?
What do you refer to when you say "this is harder"?

What are you comparing the README to?

**Comment by Cuphead74832** [comment]
> > This is harder than the README, please release a video demo for easier understanding.
> 
> ![image](https://private-user-images.githubusercontent.com/53124886/361331664-aed7f564-4f0b-4e33-bf24-692d53070efc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NjUyNTcsIm5iZiI6MTcyNTU2NDk1NywicGF0aCI6Ii81MzEyNDg4Ni8zNjEzMzE2NjQtYWVkN2Y1NjQtNGYwYi00ZTMzLWJmMjQtNjkyZDUzMDcwZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE5MzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZDU5NjkyM2YzYmRhNjI4Mjk3YTFkZjUxYjEwNzM3MzA5MmNjZTJjMjhjOTVlZGU3MDdiZTQ0MTY3ZWNiNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vxa6L_jjp-hsl2-rYj88AzFMnr-U1Vakyer2U83qAZg)

I am not interested in Unity decompiling anymore at the moment. As my future is now + reading for me is boring i am no longer going to attempt decompilation for now, this interested me at first because It was fun, now this is no longer fun to me. B U T. I really want this project to grow up as It could be one project that saves an online game from being forgotten just because the owner could no longer pay the server, or could be a project that could make a game modding community start. In other words, this tool Will be used commonly in the future.

For me this is too complicated and so left Unity for a while.

Good Night and have a nice programming journey. Issue closed.
