### ISSUE TITLE
Pitch black Scenes in unity after patching

### ISSUE THREAD

**Issue by ShadowRocks2** [nomnomab/unity-project-patcher#5]
im using the correct unity version 2022.3.9f1 and everything is fine until half way through patch the skybox goes pitch black and no matter what it wont go back to normal, even making a new scene in the project wont fix it, makes it impossible to see any assets

**Comment by nomnomab** [comment]
What game wrapper are you using? 

If using a custom game wrapper, what steps are you using for what game? 

Can you show some examples of what is happening? 

Have you checked your post processing values in the Project Settings or on the render pipeline assets (if using URP or HDRP)? 

Any other info will be useful 👍

**Comment by ShadowRocks2** [comment]
doing lethal company and i just followed this guide https://youtu.be/mZSg_R3UTak?si=d7AgiS-ctXiXbhMY&t=173 and the only game wrapper i know of was this https://github.com/nomnomab/unity-lc-project-patcher.git

**Comment by ShadowRocks2** [comment]
![Screenshot 2024-09-11 034402](https://github.com/user-attachments/assets/5aa397e7-a40e-4b7b-bc69-0455f6ef25f6)

**Comment by ShadowRocks2** [comment]
im just dumb nvm

**Comment by DavidIlie** [comment]
How did you fix it?

**Comment by ShadowRocks2** [comment]
sadly its been awhile so im not sure anymore but considering my last comment it was a mistake on my end, maybe something to do with light sources attached to the model, again dont remember at all
